version: '3'
services:
  postgres:
    image: 'postgres:14.0'
    ports:
        - '5433:5432'
    restart: always
    deploy: 
      mode: replicated
      replicas: 1
    environment:
        POSTGRES_DB: postgres
    env_file:
        - .env
  
    volumes:
        - ./db-data/postgres/:/var/lib/postgresql/data/

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass JcZ04CxaxYix0XFMJaaB
    environment:
      - SPRING_REDIS_HOST=redis
    env_file:
      - .env

  school-api:
    build: 
      context: ./../projeto-boletins
      dockerfile: ./../projeto-boletins/Dockerfile
    restart: always
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - APP_JWTEXPIRATIONMS = 8640000
    env_file:
        - .env
    deploy:
      mode: replicated
      replicas: 1
  
  mailhog:
      image: mailhog/mailhog
      container_name: 'mailhog'
      ports:
        - '1025:1025'
        - '8025:8025'
