version: '3'
services:
  school-api:
    build: 
      context: ./../projeto-boletins
      dockerfile: ./../projeto-boletins/Dockerfile
    restart: always
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - APP_JWTEXPIRATIONMS = 8640000
    env_file:
        - .env
    deploy:
      mode: replicated
      replicas: 1
  
  postgres:
    image: 'postgres:14.0'
    ports:
        - '5433:5432'
    restart: always
    deploy: 
        mode: replicated
        replicas: 1
    environment:
        POSTGRES_DB: postgres
    env_file:
        - .env
  
    volumes:
        - ./db-data/postgres/:/var/lib/postgresql/data/
  